### ISSUE TITLE
Path to certificate file doesn't work on Linux (WSL)

### ISSUE THREAD

**Issue by izaxon** [RickardPettersson/swish-api-csharp#10]
The path now contains backslashes (\). This only works on Windows, but not on Linux. It is proposed to use System.IO.Path.Combine() on line 17 in Program.cs (project SwishApiConsoleTest)..
```cs
string certificatePath = Path.Combine(Environment.CurrentDirectory, "TestCert", "Swish_Merchant_TestCertificate_1234679304.p12");
```

**Comment by RickardPettersson** [comment]
ok, looking into it

**Comment by RickardPettersson** [comment]
I have now updated the code and the NuGet package version 2.0 is on the way, Microsoft doing stuff with the package before it come available public but the code is in this repository from now.

**Comment by RickardPettersson** [comment]
I missed to say that there is in the new clients like eCommerceClient you can now have parameter for the ClientCertificate where you can put a stream so you can use your own code to get the certificate how you like and then make it as a Stream to the library to read.
