### ISSUE TITLE
HttpClient enabled even when _enableHTTPLog set to false?

### ISSUE THREAD

**Issue by ludvigbartholdsson** [RickardPettersson/swish-api-csharp#16]
I have only tested payoutClient in Emulator mode, in PayoutClient I set http log to false. Still logging!

**Comment by RickardPettersson** [comment]
ok, looking into it

**Comment by RickardPettersson** [comment]
Latest code in the repository now listening on the _enabledHTTPLog parameter, all clients have that "bug". Nuget is not updated yet going to fix some more things before that.
