### ISSUE TITLE
Possibility to return payload from MakePayoutRequest?

### ISSUE THREAD

**Issue by ludvigbartholdsson** [RickardPettersson/swish-api-csharp#17]
In production environments, for easier debugging or investigation of transaction, you usually want to store the request sent to the payment/payout-provider.

Is it possible to return Payload as a parameter here?
https://github.com/RickardPettersson/swish-api-csharp/blob/7d644e6cd4a33ea785b9bdf1b9d480bd80eb25e4/SwishApi/PayoutClient.cs#L148

**Comment by RickardPettersson** [comment]
ok, should be possible, comming back when i updated the code.

**Comment by RickardPettersson** [comment]
Latest code now have Payout in the response of the make payout function in the payout client. Nuget is not updated, comming  some day.
