### ISSUE TITLE
Add Payout webhook class

### ISSUE THREAD

**Issue by ludvigbartholdsson** [RickardPettersson/swish-api-csharp#18]
Can't find an interface or class for payout-webhook. Response looks like this with emulator. Can you add it?

![image](https://user-images.githubusercontent.com/44546168/191984201-2fb31ce2-dfd4-46ce-9e6f-622e9cdc7343.png)

**Comment by RickardPettersson** [comment]
The class is named SwishAPi.Models.PayoutRequestData

**Comment by ludvigbartholdsson** [comment]
Does not include "status"

**Comment by RickardPettersson** [comment]
there is no status in the Payload? that what you looking at seems like the callback or get status data...

**Comment by ludvigbartholdsson** [comment]
Yes, that is callback req.

**Comment by RickardPettersson** [comment]
Sorry i read wrong, its friday :)

Check the model class: SwishApi.Models.CheckPayoutRequestStatusResponse i think that the same as callback get for payout

**Comment by RickardPettersson** [comment]
I hav enot done anything except do the test console app with Payout yet, its others code i have changed.

**Comment by ludvigbartholdsson** [comment]
Yes that is great! Thank you very much. Are you able to push the other changes to Nuget? (http client, etc)

**Comment by RickardPettersson** [comment]
yes, if you dont find anything more right now i can do that :P

**Comment by ludvigbartholdsson** [comment]
Hmm, we can wait 30 min and I will let you know if I find anything else :)

**Comment by ludvigbartholdsson** [comment]
So we dont get unneccessary amounts of pushes to nuget
