### ISSUE TITLE
MakePayoutRequest amount is int, when it should be float(?)

### ISSUE THREAD

**Issue by ludvigbartholdsson** [RickardPettersson/swish-api-csharp#19]
https://github.com/RickardPettersson/swish-api-csharp/blob/c2cb540829083cff325e292bea1105c467773e73/SwishApi/PayoutClient.cs#L76

According to Swish API Docs:

"Amount to be paid. Only period/dot (”.”) are accepted as decimal character with maximum 2 digits after. Digits after separator are optional."
https://developer.swish.nu/api/payouts/v1#create-payout

**Comment by RickardPettersson** [comment]
Seems like i have done a bad decision there i fixing it.

**Comment by ludvigbartholdsson** [comment]
Thanks! Can you push to nuget after this and the other issue?

**Comment by RickardPettersson** [comment]
Latest code now have fix for this. Nuget comming
