### ISSUE TITLE
Times out when calling MakePaymentRequest

### ISSUE THREAD

**Issue by FuzzGuitar** [RickardPettersson/swish-api-csharp#2]
Hi!

Not sure if this repo is being maintained. 
Im trying to get it to work with the `test env` but I encounter a time out when calling the function MakePaymentRequest.

I tried changing _baseAPIUrl  from:
`https://mss.cpc.getswish.net` to
` https://mss.swicpc.bankgirot.se`  because I think the API might have changed.

Thank you!

**Comment by AXS-RickardPettersson** [comment]
In the latest documentation of Swish Merchant it is the right url i have in the code.

**Comment by RickardPettersson** [comment]
In the latest documentation of Swish Merchant it is the right url i have in the code.

**Comment by FuzzGuitar** [comment]
Hello and thank you for answering!

Yes you are right.  I made a misstake about the url.
I think my problem is related to the certificate. Will create new issue.
