### ISSUE TITLE
MakePayoutRequest, wrong parameter name?

### ISSUE THREAD

**Issue by ludvigbartholdsson** [RickardPettersson/swish-api-csharp#20]
https://github.com/RickardPettersson/swish-api-csharp/blob/c2cb540829083cff325e292bea1105c467773e73/SwishApi/PayoutClient.cs#L76

payerAlias => payeeAlias (phone number of customer)

**Comment by RickardPettersson** [comment]
latest code have some changed parameter names to make this more clear
