### ISSUE TITLE
Load payouts certificate as stream does not work

### ISSUE THREAD

**Issue by ludvigbartholdsson** [RickardPettersson/swish-api-csharp#21]
ClientCertificate looks like this:

           var clientCertificate = new SwishApi.Models.ClientCertificate()
            {
                CertificateAsStream = ms,
                Password = "password"
            };
I always get: No Signing Certificate found!

I tried to trace your code:

MakePayoutsRequest run: https://github.com/RickardPettersson/swish-api-csharp/blob/0cfde537722bffb9c6d58c3e9665c5231adb4f0d/SwishApi/Models/PayoutRequestEnvelope.cs#L47

In the function you run:
https://github.com/RickardPettersson/swish-api-csharp/blob/0cfde537722bffb9c6d58c3e9665c5231adb4f0d/SwishApi/Models/PayoutRequestEnvelope.cs#L49

With `signingCertificate.CertificateFilePath`. You never use `CertificateAsStream`.

**Comment by RickardPettersson** [comment]
Code fix pushed and new nuget uploaded waiting for approval so check for nuget version 2.0.3 in a hour or something
