### ISSUE TITLE
Still not working with memorystream

### ISSUE THREAD

**Issue by ludvigbartholdsson** [RickardPettersson/swish-api-csharp#22]
Tror du råkade göra lite fel här:

https://github.com/RickardPettersson/swish-api-csharp/blob/a6bfb49a26313461868db61497e214bab57804bc/SwishApi/Models/PayoutRequestEnvelope.cs#L49

Skall vara ett ! framför i if-statementet

**Comment by RickardPettersson** [comment]
Oj, lite för snabb fix där :)
Nu fixat senaste koden och ny nuget påväg up 2.0.4
