### ISSUE TITLE
Access is denied. at System.Security.Cryptography.X509Certificates

### ISSUE THREAD

**Issue by mehran-ka** [RickardPettersson/swish-api-csharp#6]
Hi
I got this Error May you please help me ?

` System.Security.Cryptography.CryptographicException: Access is denied. at System.Security.Cryptography.X509Certificates.X509Store.Add (X509Certificate2 certificate) at SwishApi.Client.PrepareHttpClientAndHandler (HttpClientHandler & handler, HttpClient & client) at SwishApi.Client.MakePaymentRumberringRestring (String)`

**Comment by RickardPettersson** [comment]
Sorry dont know what that can be.
